name: $(Date:yyyyMMdd).$(Rev:r)

trigger: none

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: azuretre-dev
    values:
      - "azuretre-dev"

variables:
    - group: '${{ parameters.environment }}'

jobs:
  - template: az_pipeline_templates/deploy_tre_reusable.yml
    parameters:
      ciGitRef: $(Build.SourceBranch)
      # e2eTestsCustomSelector: >-
      #   $[ (github.event_name == 'push' && 'extended or extended_aad') || 'extended or extended_aad or shared_services or airlock' ]
      environmentName: ${{ parameters.environment }}
      E2E_TESTS_NUMBER_PROCESSES: 1
      DEVCONTAINER_TAG: 'latest'
      AAD_TENANT_ID: $(AAD_TENANT_ID)
      ACR_NAME: $(ACR_NAME)
      AZURE_CREDENTIALS: 'AzureTRE-Dev'
      API_CLIENT_ID: $(API_CLIENT_ID)
      API_CLIENT_SECRET: $(API_CLIENT_SECRET)
      APPLICATION_ADMIN_CLIENT_ID: $(APPLICATION_ADMIN_CLIENT_ID)
      APPLICATION_ADMIN_CLIENT_SECRET: $(APPLICATION_ADMIN_CLIENT_SECRET)
      MGMT_RESOURCE_GROUP_NAME: $(MGMT_RESOURCE_GROUP_NAME)
      MS_TEAMS_WEBHOOK_URI: $(MS_TEAMS_WEBHOOK_URI)
      MGMT_STORAGE_ACCOUNT_NAME: $(MGMT_STORAGE_ACCOUNT_NAME)
      SWAGGER_UI_CLIENT_ID: $(SWAGGER_UI_CLIENT_ID)
      TEST_APP_ID: $(TEST_APP_ID)
      TEST_WORKSPACE_APP_ID: $(TEST_WORKSPACE_APP_ID)
      TEST_WORKSPACE_APP_SECRET: "$(TEST_WORKSPACE_APP_SECRET)"
      TEST_ACCOUNT_CLIENT_ID: "$(TEST_ACCOUNT_CLIENT_ID)"
      TEST_ACCOUNT_CLIENT_SECRET: "$(TEST_ACCOUNT_CLIENT_SECRET)"
      TRE_ID: $(TRE_ID)
      CI_CACHE_ACR_NAME: $(ACR_NAME)
      LOCATION: $(LOCATION)
      AZURE_ENVIRONMENT: $(AZURE_ENVIRONMENT)
      TEST_USER_NAME: $(TEST_USER_NAME)
      TEST_USER_PASSWORD: $(TEST_USER_PASSWORD)
      SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
      BUNDLES:
        - BUNDLE_TYPE: "workspace"
          BUNDLE_DIR: "./templates/workspaces/base"
        - BUNDLE_TYPE: "workspace"
          BUNDLE_DIR: "./templates/workspaces/unrestricted"
        - BUNDLE_TYPE: "workspace"
          BUNDLE_DIR: "./templates/workspaces/airlock-import-review"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/guacamole"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/azureml"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/innereye"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/gitea"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/rshiny"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/bastion"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/mlflow"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/mysql"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/health-services"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/databricks"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/ohdsi"
      SHARED_BUNDLES:
        - BUNDLE_TYPE: "shared_service"
          BUNDLE_DIR: "./templates/shared_services/firewall"
        - BUNDLE_TYPE: "shared_service"
          BUNDLE_DIR: "./templates/shared_services/gitea"
        - BUNDLE_TYPE: "shared_service"
          BUNDLE_DIR: "./templates/shared_services/admin-vm/"
        - BUNDLE_TYPE: "shared_service"
          BUNDLE_DIR: "./templates/shared_services/airlock_notifier/"
        - BUNDLE_TYPE: "shared_service"
          BUNDLE_DIR: "./templates/shared_services/certs/"
        - BUNDLE_TYPE: "shared_service"
          BUNDLE_DIR: "./templates/shared_services/cyclecloud/"
        - BUNDLE_TYPE: "shared_service"
          BUNDLE_DIR: "./templates/shared_services/sonatype-nexus-vm/"
        - BUNDLE_TYPE: "shared_service"
          BUNDLE_DIR: "./templates/shared_services/databricks-auth/"
      USER_RESOURCE_BUNDLES:
        - BUNDLE_TYPE: "user_resource"
          BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm"
          WORKSPACE_SERVICE_NAME: "tre-service-guacamole"
        - BUNDLE_TYPE: "user_resource"
          BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm"
          WORKSPACE_SERVICE_NAME: "tre-service-guacamole"
        - BUNDLE_TYPE: "user_resource"
          BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-export-reviewvm"
          WORKSPACE_SERVICE_NAME: "tre-service-guacamole"
        - BUNDLE_TYPE: "user_resource"
          BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-import-reviewvm"
          WORKSPACE_SERVICE_NAME: "tre-service-guacamole"
