name: $(Date:yyyyMMdd).$(Rev:r)

trigger: none

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: azuretre-dev
    values:
      - "azuretre-dev"

variables:
    - group: '${{ parameters.environment }}'

jobs:
- job: 
  displayName: 'Build RShiny App'
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'My ACR'
      repository: 'fsdf'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
