name: $(Date:yyyyMMdd).$(Rev:r)

trigger: none

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: azuretre-dev
    values:
      - "azuretre-dev"

variables:
    - group: ${{ parameters.environment }}

jobs:
  - template: az_pipeline_templates/deploy_tre_reusable.yml
    parameters:
      ciGitRef: $(Build.SourceBranch)
      # e2eTestsCustomSelector: >-
      #   $[ (github.event_name == 'push' && 'extended or extended_aad') || 'extended or extended_aad or shared_services or airlock' ]
      environmentName: ${{ parameters.environment }}
      E2E_TESTS_NUMBER_PROCESSES: 1
      DEVCONTAINER_TAG: 'latest'
      AAD_TENANT_ID: $(AAD_TENANT_ID)
      ACR_NAME: $(ACR_NAME)
      AZURE_CREDENTIALS: $(AZURE_CREDENTIALS)
      API_CLIENT_ID: $(API_CLIENT_ID)
      API_CLIENT_SECRET: $(API_CLIENT_SECRET)
      APPLICATION_ADMIN_CLIENT_ID: $(APPLICATION_ADMIN_CLIENT_ID)
      APPLICATION_ADMIN_CLIENT_SECRET: $(APPLICATION_ADMIN_CLIENT_SECRET)
      MGMT_RESOURCE_GROUP_NAME: $(MGMT_RESOURCE_GROUP_NAME)
      MS_TEAMS_WEBHOOK_URI: $(MS_TEAMS_WEBHOOK_URI)
      MGMT_STORAGE_ACCOUNT_NAME: $(MGMT_STORAGE_ACCOUNT_NAME)
      SWAGGER_UI_CLIENT_ID: $(SWAGGER_UI_CLIENT_ID)
      TEST_APP_ID: $(TEST_APP_ID)
      TEST_WORKSPACE_APP_ID: $(TEST_WORKSPACE_APP_ID)
      TEST_WORKSPACE_APP_SECRET: "$(TEST_WORKSPACE_APP_SECRET)"
      TEST_ACCOUNT_CLIENT_ID: "$(TEST_ACCOUNT_CLIENT_ID)"
      TEST_ACCOUNT_CLIENT_SECRET: "$(TEST_ACCOUNT_CLIENT_SECRET)"
      TRE_ID: $(TRE_ID)
      CI_CACHE_ACR_NAME: $(ACR_NAME)
