name: $(Date:yyyyMMdd).$(Rev:r)

trigger: none

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: azuretre-dev
    values:
      - "azuretre-dev"

variables:
    - group: '${{ parameters.environment }}'
    - name: DOCKER_DIRECTORY
      value: 'templates/workspace_services/rshiny/rshiny-app'
    - name: DOCKER_FILE
      value: 'templates/workspace_services/rshiny/rshiny-app/Dockerfile'
    - name: VERSION_FILE
      value: 'templates/workspace_services/rshiny/version.txt'

jobs:
- job: 
  displayName: 'Build RShiny App'
  steps:
  - task: AzureCLI@2
    displayName: 'Build and Push'
    inputs:
      azureSubscription: $(AZURE_CREDENTIALS)
      addSpnToEnvironment: true
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        version_file='$(VERSION_FILE)'
        acr_name='$(ACR_NAME)'
        image_name_prefix="microsoft/azuretre"

        version_line=$(cat "${version_file}")
        version_array=( ${version_line//=/ } )
        version="${version_array[1]//\"}"

        ./devops/scripts/login_acr.sh $acr_name

        acr_domain_suffix=`az cloud show --query suffixes.acrLoginServerEndpoint --output tsv`
        acr_fqdn="${acr_name}${acr_domain_suffix}"
        full_image_name_prefix:=${acr_fqdn}/${image_name_prefix}

        docker build -t "${full_image_name_prefix}/${image_name}:${version}" -f "$(DOCKER_FILE)" "$(DOCKER_DIRECTORY)"
        docker push "${full_image_name_prefix}/${image_name}:${version}"

