name: $(Date:yyyyMMdd).$(Rev:r)

trigger: none

parameters:
  - name: deployStages
    displayName: Deploy Stages
    type: string
    default: 'all'
    values:
      - "all"
      - "core"
      - "workspace-bundles"
      - "user-resource-bundles"
      - "shared-bundles"
  - name: environment
    displayName: Environment
    type: string
    default: azuretre-dev
    values:
      - "azuretre-dev"
  - name: runE2ECustomTests
    displayName: Run E2E Custom Tests
    type: boolean
    default: 'false'
  - name: e2eTestsCustomSelector
    displayName: E2E Tests Custom Selector
    type: string
    default: "extended or extended_aad"
    values:
      - "extended or extended_aad"
      - "extended or extended_aad or shared_services or airlock"
  - name: deployFirewall
    displayName: Deploy Firewall
    type: boolean
    default: 'false'
  - name: enableBastion
    displayName: Enable Bastion Host
    type: boolean
    default: 'false'

variables:
    - group: '${{ parameters.environment }}'

jobs:
  - template: az_pipeline_templates/deploy_tre_reusable.yml
    parameters:
      deployStages: ${{ parameters.deployStages }}
      ciGitRef: $(Build.SourceBranch)
      environmentName: ${{ parameters.environment }}
      ${{ if eq(parameters.runE2ECustomTests, 'true') }}:
        e2eTestsCustomSelector: ${{ parameters.e2eTestsCustomSelector }}
      ${{ else }}:
        e2eTestsCustomSelector: ""
      E2E_TESTS_NUMBER_PROCESSES: '1'
      DEVCONTAINER_TAG: 'latest'
      AAD_TENANT_ID: $(AAD_TENANT_ID)
      ACR_NAME: $(ACR_NAME)
      AZURE_CREDENTIALS: 'AzureTRE-Dev'
      API_CLIENT_ID: $(API_CLIENT_ID)
      API_CLIENT_SECRET: $(API_CLIENT_SECRET)
      APPLICATION_ADMIN_CLIENT_ID: $(APPLICATION_ADMIN_CLIENT_ID)
      APPLICATION_ADMIN_CLIENT_SECRET: $(APPLICATION_ADMIN_CLIENT_SECRET)
      MGMT_RESOURCE_GROUP_NAME: $(MGMT_RESOURCE_GROUP_NAME)
      MS_TEAMS_WEBHOOK_URI: $(MS_TEAMS_WEBHOOK_URI)
      MGMT_STORAGE_ACCOUNT_NAME: $(MGMT_STORAGE_ACCOUNT_NAME)
      SWAGGER_UI_CLIENT_ID: $(SWAGGER_UI_CLIENT_ID)
      TEST_APP_ID: $(TEST_APP_ID)
      TEST_WORKSPACE_APP_ID: $(TEST_WORKSPACE_APP_ID)
      TEST_WORKSPACE_APP_SECRET: "$(TEST_WORKSPACE_APP_SECRET)"
      TEST_ACCOUNT_CLIENT_ID: "$(TEST_ACCOUNT_CLIENT_ID)"
      TEST_ACCOUNT_CLIENT_SECRET: "$(TEST_ACCOUNT_CLIENT_SECRET)"
      TRE_ID: $(TRE_ID)
      CI_CACHE_ACR_NAME: $(ACR_NAME)
      LOCATION: $(LOCATION)
      AZURE_ENVIRONMENT: $(AZURE_ENVIRONMENT)
      TEST_USER_NAME: $(TEST_USER_NAME)
      TEST_USER_PASSWORD: $(TEST_USER_PASSWORD)
      SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
      WORKSPACE_APP_SERVICE_PLAN_SKU: 'P1v2'
      RESOURCE_PROCESSOR_NUMBER_PROCESSES_PER_INSTANCE: "5"
      ENABLE_SWAGGER: 'false'
      ${{ if eq(parameters.enableBastion , 'true') }}:
        ENABLE_BASTION: 'true'
      DEPLOY_FIREWALL: ${{ parameters.deployFirewall }}
      CORE_ADDRESS_SPACE: '10.0.0.0/22'
      CORE_APP_SERVICE_PLAN_SKU: 'P1v2'
      TRE_ADDRESS_SPACE: '10.0.0.0/16'
      BUILD_AGENTS_RESOURCE_GROUP_NAME: $(BUILD_AGENTS_RESOURCE_GROUP_NAME)
      BUILD_AGENTS_VNET_NAME: $(BUILD_AGENTS_VNET_NAME)
      BUILD_AGENTS_SUBNET_NAME: $(BUILD_AGENTS_SUBNET_NAME)
      BUNDLES:
        - BUNDLE_TYPE: "workspace"
          BUNDLE_DIR: "./templates/workspaces/base"
          BUNDLE_NAME: "base"
        - BUNDLE_TYPE: "workspace"
          BUNDLE_DIR: "./templates/workspaces/unrestricted"
          BUNDLE_NAME: "unrestricted"
        - BUNDLE_TYPE: "workspace"
          BUNDLE_DIR: "./templates/workspaces/airlock-import-review"
          BUNDLE_NAME: "airlock_import_review"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/guacamole"
          BUNDLE_NAME: "guacamole"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/azureml"
          BUNDLE_NAME: "azureml"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/innereye"
          BUNDLE_NAME: "innereye"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/gitea"
          BUNDLE_NAME: "gitea"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/rshiny"
          BUNDLE_NAME: "rshiny"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/bastion"
          BUNDLE_NAME: "bastion"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/mlflow"
          BUNDLE_NAME: "mlflow"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/mysql"
          BUNDLE_NAME: "mysql"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/health-services"
          BUNDLE_NAME: "health_services"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/databricks"
          BUNDLE_NAME: "databricks"
        - BUNDLE_TYPE: "workspace_service"
          BUNDLE_DIR: "./templates/workspace_services/ohdsi"
          BUNDLE_NAME: "ohdsi"
      SHARED_BUNDLES:
        - BUNDLE_TYPE: "shared_service"
          BUNDLE_DIR: "./templates/shared_services/firewall"
          BUNDLE_NAME: "firewall"
        - BUNDLE_TYPE: "shared_service"
          BUNDLE_DIR: "./templates/shared_services/gitea"
          BUNDLE_NAME: "gitea_shared"
        - BUNDLE_TYPE: "shared_service"
          BUNDLE_DIR: "./templates/shared_services/admin-vm/"
          BUNDLE_NAME: "admin_vm"
        - BUNDLE_TYPE: "shared_service"
          BUNDLE_DIR: "./templates/shared_services/airlock_notifier/"
          BUNDLE_NAME: "airlock_notifier"
        - BUNDLE_TYPE: "shared_service"
          BUNDLE_DIR: "./templates/shared_services/certs/"
          BUNDLE_NAME: "certs"
        - BUNDLE_TYPE: "shared_service"
          BUNDLE_DIR: "./templates/shared_services/cyclecloud/"
          BUNDLE_NAME: "cyclecloud"
        - BUNDLE_TYPE: "shared_service"
          BUNDLE_DIR: "./templates/shared_services/sonatype-nexus-vm/"
          BUNDLE_NAME: "sonatype-nexus-vm"
        - BUNDLE_TYPE: "shared_service"
          BUNDLE_DIR: "./templates/shared_services/databricks-auth/"
          BUNDLE_NAME: "databricks_auth"
      USER_RESOURCE_BUNDLES:
        - BUNDLE_TYPE: "user_resource"
          BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm"
          BUNDLE_NAME: "guacamole_azure_windowsvm"
          WORKSPACE_SERVICE_NAME: "tre-service-guacamole"
        - BUNDLE_TYPE: "user_resource"
          BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm"
          BUNDLE_NAME: "guacamole_azure_linuxvm"
          WORKSPACE_SERVICE_NAME: "tre-service-guacamole"
        - BUNDLE_TYPE: "user_resource"
          BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-export-reviewvm"
          BUNDLE_NAME: "guacamole_azure_export_reviewvm"
          WORKSPACE_SERVICE_NAME: "tre-service-guacamole"
        - BUNDLE_TYPE: "user_resource"
          BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-import-reviewvm"
          BUNDLE_NAME: "guacamole_azure_import_reviewvm"
          WORKSPACE_SERVICE_NAME: "tre-service-guacamole"
        - BUNDLE_TYPE: "user_resource"
          BUNDLE_DIR: "./templates/workspace_services/bastion/user_resources/bastion-azure-linuxvm"
          BUNDLE_NAME: "bastion_azure_linuxvm"
          WORKSPACE_SERVICE_NAME: "tre-service-bastion"
        - BUNDLE_TYPE: "user_resource"
          BUNDLE_DIR: "./templates/workspace_services/bastion/user_resources/bastion-azure-windowsvm"
          BUNDLE_NAME: "bastion_azure_windowsvm"
          WORKSPACE_SERVICE_NAME: "tre-service-bastion"
