parameters:
  - name: ciGitRef
    displayName: Git reference
    type: string
    default: ''
  - name: environmentName
    displayName: Environment name
    type: string
    default: ''
  - name: E2E_TESTS_NUMBER_PROCESSES
    displayName: Number of processes for e2e tests
    type: number
    default: "1"
  - name: DEVCONTAINER_TAG
    displayName: Devcontainer tag
    type: string
    default: 'latest'
  - name: AAD_TENANT_ID
    displayName: AAD tenant ID
    type: string
    default: ''
  - name: ACR_NAME
    displayName: ACR name
    type: string
    default: ''
  - name: AZURE_CREDENTIALS
    displayName: Azure credentials
    type: string
    default: ''
  - name: API_CLIENT_ID
    displayName: API client ID
    type: string
    default: ''
  - name: API_CLIENT_SECRET
    displayName: API client secret
    type: string
    default: ''
  - name: APPLICATION_ADMIN_CLIENT_ID
    displayName: Application admin client ID
    type: string
    default: ''
  - name: APPLICATION_ADMIN_CLIENT_SECRET
    displayName: Application admin client secret
    type: string
    default: ''
  - name: MGMT_RESOURCE_GROUP_NAME
    displayName: Management resource group name
    type: string
    default: ''
  - name: MS_TEAMS_WEBHOOK_URI
    displayName: MS Teams webhook URI
    type: string
    default: ''
  - name: MGMT_STORAGE_ACCOUNT_NAME
    displayName: Management storage account name
    type: string
    default: ''
  - name: SWAGGER_UI_CLIENT_ID
    displayName: Swagger UI client ID
    type: string
    default: ''
  - name: TEST_APP_ID
    displayName: Test app ID
    type: string
    default: ''
  - name: TEST_WORKSPACE_APP_ID
    displayName: Test workspace app ID
    type: string
    default: ''
  - name: TEST_WORKSPACE_APP_SECRET
    displayName: Test workspace app secret
    type: string
    default: ''
  - name: TEST_ACCOUNT_CLIENT_ID
    displayName: Test account client ID
    type: string
    default: ''
  - name: TEST_ACCOUNT_CLIENT_SECRET
    displayName: Test account client secret
    type: string
    default: ''
  - name: TRE_ID
    displayName: TRE ID
    type: string
    default: ''
  - name: CI_CACHE_ACR_NAME
    displayName: CI cache ACR name
    type: string
    default: ''
  - name: e2eTestsCustomSelector
    displayName: E2E tests custom selector
    type: string
    default: ''

jobs:
 - job: test
   pool:
      vmImage: ubuntu-latest
   steps:
    - 'bash': |
        echo "Hello world"
