name: Export Secrets to Artifact

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to run this workflow in
        type: environment
        default: poc
        required: true

env:
  PREFIX_SECRETS: 'SECRETS_'

jobs:
    export-secrets-env:
      name: Export Secrets (env)
      runs-on: windows-latest
      environment: ${{ github.event.inputs.environment }}
      steps:
        - name: Export Secrets to CSV (env)
          uses: martins-vds/export-secrets-action@v1
          env:
            SECRETS_AAD_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}
            SECRETS_ACR_NAME: ${{ secrets.ACR_NAME }}
            SECRETS_AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
            SECRETS_API_CLIENT_ID: ${{ secrets.API_CLIENT_ID }}
            SECRETS_API_CLIENT_SECRET: ${{ secrets.API_CLIENT_SECRET }}
            SECRETS_APPLICATION_ADMIN_CLIENT_ID: ${{ secrets.APPLICATION_ADMIN_CLIENT_ID }}
            SECRETS_APPLICATION_ADMIN_CLIENT_SECRET: ${{ secrets.APPLICATION_ADMIN_CLIENT_SECRET }}
            SECRETS_MGMT_RESOURCE_GROUP_NAME: ${{ secrets.MGMT_RESOURCE_GROUP_NAME }}
            SECRETS_MS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
            SECRETS_MGMT_STORAGE_ACCOUNT_NAME: ${{ secrets.MGMT_STORAGE_ACCOUNT_NAME }}
            SECRETS_SWAGGER_UI_CLIENT_ID: ${{ secrets.SWAGGER_UI_CLIENT_ID }}
            SECRETS_TEST_APP_ID: ${{ secrets.TEST_APP_ID }}
            SECRETS_TEST_WORKSPACE_APP_ID: ${{ secrets.TEST_WORKSPACE_APP_ID }}
            SECRETS_TEST_WORKSPACE_APP_SECRET: "${{ secrets.TEST_WORKSPACE_APP_SECRET }}"
            SECRETS_TEST_ACCOUNT_CLIENT_ID: "${{ secrets.TEST_ACCOUNT_CLIENT_ID }}"
            SECRETS_TEST_ACCOUNT_CLIENT_SECRET: "${{ secrets.TEST_ACCOUNT_CLIENT_SECRET }}"
            SECRETS_TRE_ID: ${{ secrets.TRE_ID }}
            SECRETS_CI_CACHE_ACR_NAME: ${{ secrets.ACR_NAME }}
            SECRETS_LOCATION: ${{ secrets.LOCATION }}
            SECRETS_TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
            SECRETS_TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
          with:
            repository: ${{ github.repository }}
            secrets-prefix: 'SECRETS_'
            secrets-type: 'env'
            environment-name: '${{ github.event.inputs.environment }}'
